name: Build

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install -d --system
      - name: Lint with flake8
        run: |
          pipenv install flake8
          pipenv run flake8 --ignore F401,W605,W503 hermes

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install -d --system
      - name: Run Tests
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: pipenv run pytest

  docker:
    needs: [lint, test]
    name: Push container image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set Commit Hash
        id: commit_hash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          target: cli
          tags: zydambat/hermes:${{ steps.commit_hash.outputs.sha_short }}
          push: true
